#ifndef KERNEL_H
#define KERNEL_H
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
#include <drivers/vga/vga.h>
//#include <drivers/gpu/gpu.h>
#include <drivers/descriptor/descriptor.h>
#include <drivers/keyboard/keyboard.h>
#include <drivers/pit/pit.h>
#include <drivers/syscall/syscall.h>
#include <multiboot/multiboot.h>
#include <memory/pmm/pmm.h>
#include <memory/vmm/vmm.h>
#include <processes/processes.h>
#include <kshell/kshell.h>
//#include "../filesystem/ext2/fs.h"
//#include "../filesystem/ide/ide.h"
#endif
